version: '2'
services:

  entrance:
    build: ./entrance
    depends_on:
      - manager
      - teller
    ports:
      - "8080:80"

  manager:
    build: ./manager
    depends_on:
      - vault
    ports:
      - "3000"
    environment:
      HASHING_KEY: 'please_change'
      ROOT_USERNAME: 'CryptoGod'
      ROOT_PASSWORD: 'please_change'
      ROOT_EMAIL: 'cryptogod@wakeup.coffee'
      TOKEN_KEY: 'please_change'


  teller:
    build: ./teller
    ports:
      - "80"

  vault:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./img:/img

volumes:
  data:
    driver: local
