version: '2'
services:

  entrance:
    build: ./entrance
    depends_on:
      - manager
      - teller
    ports:
      - "8080:80"

  manager:
    build: ./manager
    depends_on:
     - vault
    ports:
      - "3000"


  teller:
    build: ./teller
    ports:
      - "80"

  vault:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

volumes:
  data:
    driver: local
